version: '3.8'

services:
  app:
    build: .
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - MONGO_URI=mongodb://mongo:27017/chat-app
      - JWT_SECRET=your_jwt_secret_key
      - REDIS_URL=redis://redis:6379
    volumes:
      - ./uploads:/app/uploads
    depends_on:
      - mongo
      - redis
    networks:
      - chat-network

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - chat-network

  redis:
    image: redis:latest
    ports:
      - "6378:6379"
    networks:
      - chat-network

volumes:
  mongo-data:


networks:
  chat-network:
    driver: bridge
